//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winner.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACPPACKDOUBLEACTING
    {
        public int id { get; set; }
        public string Firstimg { get; set; }
        public string SecondImg { get; set; }
        public string tanksize { get; set; }
        public string width { get; set; }
        public string length { get; set; }
        public string HEIGHT { get; set; }
    }
}
