//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winner.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTRIDGESProductdetail
    {
        public int id { get; set; }
        public Nullable<int> CARTRIDGESID { get; set; }
        public string partno { get; set; }
        public string cavity { get; set; }
        public string price { get; set; }
        public string Firstimg { get; set; }
        public string secondimg { get; set; }
        public string maxoprationgprussure { get; set; }
        public string ratedflow { get; set; }
        public string cavitytooling { get; set; }
        public string installationtorque { get; set; }
        public string weight { get; set; }
        public string CRACKINGPRESSURE { get; set; }
    
        public virtual CARTRIDGE CARTRIDGE { get; set; }
    }
}
