//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winner.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTRIDGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARTRIDGE()
        {
            this.CARTRIDGESProducts = new HashSet<CARTRIDGESProduct>();
            this.CARTRIDGESProductdetails = new HashSet<CARTRIDGESProductdetail>();
            this.OPTIONALBODies = new HashSet<OPTIONALBODY>();
            this.OPTIONALCOILs = new HashSet<OPTIONALCOIL>();
            this.OPTIONALHIRSHMANLEDs = new HashSet<OPTIONALHIRSHMANLED>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string picurl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTRIDGESProduct> CARTRIDGESProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTRIDGESProductdetail> CARTRIDGESProductdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPTIONALBODY> OPTIONALBODies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPTIONALCOIL> OPTIONALCOILs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPTIONALHIRSHMANLED> OPTIONALHIRSHMANLEDs { get; set; }
    }
}
