//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winner.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTIONALBODY
    {
        public int id { get; set; }
        public Nullable<int> CARTRIDGESID { get; set; }
        public string PARTNO { get; set; }
        public string MATERIAL { get; set; }
        public string MAXPRESSURE { get; set; }
        public string PRICE { get; set; }
        public string Firstimg { get; set; }
        public string secondimg { get; set; }
        public string cavity { get; set; }
        public string weight { get; set; }
        public string PORTSIZE { get; set; }
    
        public virtual CARTRIDGE CARTRIDGE { get; set; }
    }
}
