//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winner.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class winnerEntities : DbContext
    {
        public winnerEntities()
            : base("name=winnerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACPPACKDOUBLEACTING> ACPPACKDOUBLEACTINGs { get; set; }
        public virtual DbSet<ACPPACKDUTYCYCLE> ACPPACKDUTYCYCLEs { get; set; }
        public virtual DbSet<ACPPACKFLOWRATE> ACPPACKFLOWRATEs { get; set; }
        public virtual DbSet<ACPPACKFURTHERCOMMENT> ACPPACKFURTHERCOMMENTS { get; set; }
        public virtual DbSet<ACPPACKMOTORSIZE> ACPPACKMOTORSIZEs { get; set; }
        public virtual DbSet<ACPPACKOPERATION> ACPPACKOPERATIONs { get; set; }
        public virtual DbSet<ACPPACKPENDENT> ACPPACKPENDENTs { get; set; }
        public virtual DbSet<ACPPACKPOSITIONOFMOTOR> ACPPACKPOSITIONOFMOTORs { get; set; }
        public virtual DbSet<ACPPACKPRESSURESETTING> ACPPACKPRESSURESETTINGs { get; set; }
        public virtual DbSet<ACPPACKPT> ACPPACKPTs { get; set; }
        public virtual DbSet<ACPPACKQUANTITY> ACPPACKQUANTITies { get; set; }
        public virtual DbSet<ACPPACKRESERVOIRSIZE> ACPPACKRESERVOIRSIZEs { get; set; }
        public virtual DbSet<ACPPACKSINGLEACTING> ACPPACKSINGLEACTINGs { get; set; }
        public virtual DbSet<ACPPACKTYPEOFSYSTEM> ACPPACKTYPEOFSYSTEMs { get; set; }
        public virtual DbSet<ACPPACKVOLTAGE> ACPPACKVOLTAGEs { get; set; }
        public virtual DbSet<CARTRIDGE> CARTRIDGES { get; set; }
        public virtual DbSet<CARTRIDGESProduct> CARTRIDGESProducts { get; set; }
        public virtual DbSet<CARTRIDGESProductdetail> CARTRIDGESProductdetails { get; set; }
        public virtual DbSet<DCPPACK_SYSTEM> DCPPACK_SYSTEMs { get; set; }
        public virtual DbSet<DCPPACKCOMMENT> DCPPACKCOMMENTS { get; set; }
        public virtual DbSet<DCPPACKDOUBLEEACTING> DCPPACKDOUBLEEACTINGs { get; set; }
        public virtual DbSet<DCPPACKFLOWRATE> DCPPACKFLOWRATEs { get; set; }
        public virtual DbSet<DCPPACKMOTOR_SIZE> DCPPACKMOTOR_SIZEs { get; set; }
        public virtual DbSet<DCPPACKMOTORPOSITION> DCPPACKMOTORPOSITIONs { get; set; }
        public virtual DbSet<DCPPACKOPERATION> DCPPACKOPERATIONs { get; set; }
        public virtual DbSet<DCPPACKPENDENT> DCPPACKPENDENTs { get; set; }
        public virtual DbSet<DCPPACKPRESSURESETTING> DCPPACKPRESSURESETTINGs { get; set; }
        public virtual DbSet<DCPPACKPT> DCPPACKPTs { get; set; }
        public virtual DbSet<DCPPACKQUANTITY> DCPPACKQUANTITies { get; set; }
        public virtual DbSet<DCPPACKRESERVOIRSIZE> DCPPACKRESERVOIRSIZEs { get; set; }
        public virtual DbSet<DCPPACKSINGLEACTING> DCPPACKSINGLEACTINGs { get; set; }
        public virtual DbSet<DCPPACKVOLTAGE> DCPPACKVOLTAGEs { get; set; }
        public virtual DbSet<Equivalent> Equivalents { get; set; }
        public virtual DbSet<OPTIONALBODY> OPTIONALBODies { get; set; }
        public virtual DbSet<OPTIONALCOIL> OPTIONALCOILs { get; set; }
        public virtual DbSet<OPTIONALHIRSHMANLED> OPTIONALHIRSHMANLEDs { get; set; }
    }
}
